name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: daeunhan/2024-beotkkotthon-team-10-be-spring
          stage: main
          yaml: |
            name: cen
            app: java@17
            options:
              ports: 8080
              env:
                - name: DB_url
                  value: 34.64.244.32
                - name: DB_port
                  value: "3306"
                - name: DB_dataBaseName
                  value: cen
                - name: DB_name
                  value: han
                - name: DB_password
                  value: cen1234
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
